require 'bundler/setup'
require 'helix_runtime/build_task'
require 'rake/testtask'

HelixRuntime::BuildTask.new("turbo_blank") 

task :benchmark => :build do
  exec "ruby -Ilib benchmark.rb"
end

Rake::TestTask.new(:test) do |t|
  t.libs << "test"
  t.libs << "lib"
  t.test_files = FileList["test/**/*_test.rb"]
end

task :test => :build

task :default => :test
